export interface Product {
  id: string
  segment: string
  sub_segment: string
  name: string
  category: string
  packaging: string
  volume: string
  unit: string
}

export const products: Product[] = [
  {
    id: "1",
    segment: "Household",
    sub_segment: "Liquid",
    name: "Detergent Liquid for Top Load",
    category: "Detergent Liquid for Top Load",
    packaging: "Pouch",
    volume: "850",
    unit: "ML",
  },
  {
    id: "2",
    segment: "Household",
    sub_segment: "Powder",
    name: "Detergent Powder for Front Load",
    category: "Detergent Powder for Front Load",
    packaging: "Pouch",
    volume: "1,000",
    unit: "KG",
  },
  {
    id: "3",
    segment: "Household",
    sub_segment: "Powder",
    name: "Detergent Powder for Top Load",
    category: "Detergent Powder for Top Load",
    packaging: "Pouch",
    volume: "1,000",
    unit: "KG",
  },
  {
    id: "4",
    segment: "Household",
    sub_segment: "Powder",
    name: "Detergent Powder",
    category: "Detergent Powder",
    packaging: "Pouch",
    volume: "1,000",
    unit: "KG",
  },
  {
    id: "5",
    segment: "Household",
    sub_segment: "Soap",
    name: "Detergent Soap",
    category: "Detergent Soap",
    packaging: "Soap Cake",
    volume: "230",
    unit: "GM",
  },
  {
    id: "6",
    segment: "Household",
    sub_segment: "Soap",
    name: "Dishwash Soap",
    category: "Dishwash Soap",
    packaging: "Dish Wash",
    volume: "110",
    unit: "GM",
  },
  {
    id: "7",
    segment: "Household",
    sub_segment: "Liquid",
    name: "Dish Wash Liquid",
    category: "Dish Wash Liquid",
    packaging: "Pouch",
    volume: "1,900",
    unit: "ML",
  },
  {
    id: "8",
    segment: "Household",
    sub_segment: "Liquid",
    name: "Fabrics Softener Liquid",
    category: "Fabrics Softener Liquid",
    packaging: "Bottle",
    volume: "900",
    unit: "ML",
  },
  {
    id: "9",
    segment: "Household",
    sub_segment: "Liquid",
    name: "Soap Oil Hand Wash Liquid",
    category: "Soap Oil Hand Wash Liquid",
    packaging: "Pouch",
    volume: "750",
    unit: "ML",
  },
  {
    id: "10",
    segment: "Household",
    sub_segment: "Liquid",
    name: "Dish Wash Liquid",
    category: "Dish Wash Liquid",
    packaging: "Bottle",
    volume: "750",
    unit: "ML",
  },
  {
    id: "11",
    segment: "Household",
    sub_segment: "Liquid",
    name: "Floor Cleaner Liquid",
    category: "Floor Cleaner Liquid",
    packaging: "Bottle",
    volume: "975",
    unit: "ML",
  },
  {
    id: "12",
    segment: "Household",
    sub_segment: "Liquid",
    name: "Glass Cleaner Liquid",
    category: "Glass Cleaner Liquid",
    packaging: "Bottle",
    volume: "500",
    unit: "ML",
  },
  {
    id: "13",
    segment: "Household",
    sub_segment: "Liquid",
    name: "Kitchen Cleaner Liquid",
    category: "Kitchen Cleaner Liquid",
    packaging: "Bottle",
    volume: "450",
    unit: "ML",
  },
  {
    id: "14",
    segment: "Household",
    sub_segment: "Liquid",
    name: "Phenoil Liquid",
    category: "Phenoil Liquid",
    packaging: "Bottle",
    volume: "850",
    unit: "ML",
  },
  {
    id: "15",
    segment: "Household",
    sub_segment: "Liquid",
    name: "Toilet Cleaner",
    category: "Toilet Cleaner",
    packaging: "Bottle",
    volume: "950",
    unit: "ML",
  },
  {
    id: "16",
    segment: "Household",
    sub_segment: "Soap",
    name: "Dishwash Soap Round",
    category: "Dishwash Soap Round",
    packaging: "Round Plastic",
    volume: "250",
    unit: "GM",
  },
  {
    id: "17",
    segment: "Household",
    sub_segment: "Liquid",
    name: "Multi Purpose Cleaner 1Ltr",
    category: "Multi Purpose Cleaner 1Ltr",
    packaging: "Bottle",
    volume: "950",
    unit: "ML",
  },
  {
    id: "18",
    segment: "Household",
    sub_segment: "Liquid",
    name: "Phenyl 5Ltr",
    category: "Phenyl 5Ltr",
    packaging: "Can",
    volume: "5,000",
    unit: "ML",
  },
  {
    id: "19",
    segment: "Household",
    sub_segment: "Liquid",
    name: "Perfumed Phenyl 5Ltr [Rose]",
    category: "Perfumed Phenyl 5Ltr [Rose]",
    packaging: "Can",
    volume: "5,000",
    unit: "ML",
  },
  {
    id: "20",
    segment: "Household",
    sub_segment: "Liquid",
    name: "Perfumed Phenyl 5Ltr [Lemon]",
    category: "Perfumed Phenyl 5Ltr [Lemon]",
    packaging: "Can",
    volume: "5,000",
    unit: "ML",
  },
  {
    id: "21",
    segment: "Commerical",
    sub_segment: "Liquid",
    name: "Marble Granites Cleaner 1Ltr",
    category: "Marble Granites Cleaner 1Ltr",
    packaging: "Bottle",
    volume: "950",
    unit: "ML",
  },
  {
    id: "22",
    segment: "Commerical",
    sub_segment: "Liquid",
    name: "Room Freshner Liquid 1Ltr",
    category: "Room Freshner Liquid 1Ltr",
    packaging: "Bottle",
    volume: "950",
    unit: "ML",
  },
  {
    id: "23",
    segment: "Commerical",
    sub_segment: "Liquid",
    name: "Furniture Polish Liquid 1Ltr",
    category: "Furniture Polish Liquid 1Ltr",
    packaging: "Bottle",
    volume: "950",
    unit: "ML",
  },
  {
    id: "24",
    segment: "Commerical",
    sub_segment: "Mats",
    name: "Urinal Mat Rectangle",
    category: "Urinal Mat Rectangle",
    packaging: "Pieces",
    volume: "",
    unit: "",
  },
  {
    id: "25",
    segment: "Commerical",
    sub_segment: "Mats",
    name: "Urinal Mat Round Bag",
    category: "Urinal Mat Round Bag",
    packaging: "Pieces",
    volume: "",
    unit: "",
  },
  {
    id: "26",
    segment: "Commerical",
    sub_segment: "Mats",
    name: "Urinal Blocks",
    category: "Urinal Blocks",
    packaging: "Pieces",
    volume: "439",
    unit: "GM",
  },
  {
    id: "27",
    segment: "Commerical",
    sub_segment: "Liquid",
    name: "Toilet Cleaner 5Ltr",
    category: "Toilet Cleaner 5Ltr",
    packaging: "Can",
    volume: "5,000",
    unit: "ML",
  },
  {
    id: "28",
    segment: "Commerical",
    sub_segment: "Liquid",
    name: "Glass Clener 5Ltr",
    category: "Glass Clener 5Ltr",
    packaging: "Can",
    volume: "5,000",
    unit: "ML",
  },
  {
    id: "29",
    segment: "Commerical",
    sub_segment: "Liquid",
    name: "Cleaning Acid 5Ltr",
    category: "Cleaning Acid 5Ltr",
    packaging: "Can",
    volume: "5,000",
    unit: "ML",
  },
  {
    id: "30",
    segment: "Commerical",
    sub_segment: "Liquid",
    name: "Hand Wash Rose 5Ltr",
    category: "Hand Wash Rose 5Ltr",
    packaging: "Can",
    volume: "5,000",
    unit: "ML",
  },
]
